# Generated by Django 5.1.3 on 2024-11-09 11:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("surname", models.CharField(blank=True, max_length=100, null=True)),
                ("phone_prefix", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("amount_lost", models.FloatField(blank=True, null=True)),
                ("agree_to_be_called", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "investor_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
